- name: Update cache
  become: yes
  ansible.builtin.apt:
    autoclean: yes 

- name: Remove useless packages from the cache  
  become: yes
  ansible.builtin.apt:
    autoclean: yes 

- name: Update all packages to their latest version
  become: yes
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Remove dependencies that are no longer required
  become: yes
  ansible.builtin.apt:
    autoremove: yes