
- name: Create the Valheim Service Template
  become: yes
  template:
    src: "{{ valheim_service_template }}"  
    dest: "{{ valheim_service_location }}"

- name: Enable the Valheim Service
  become: yes
  ansible.builtin.service:
    name: valheim
    enabled: yes

- name: Start the Valheim Service
  become: yes
  ansible.builtin.service:
    name: valheim
    state: started
